pull_request_rules:
  - name: automatic merge of bot 🤖 (low priority)
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=test
      - base=main
    actions:
      merge:
