# This file must be updated, committed and pushed for your
# SLIC Starter-based application deployment to work
sourceRepo:
  # This should be changed to match your own repo and branch
  owner: direnakkocdemir
  name: slic-starter
  branch: docs-build

domainConfig:
  # Set 'nsDomain' to an empty string ('') if you are not using custom domains. Do not remove it.
  nsDomain: ''
  siteBucketPrefix: my-slic-watch
  # Set 'siteBucketPrefix' if you are not using custom domains
  # It will be used, along with the stage value as a bucket name
  # for frontend assets so it should be unique.
  # siteBucketPrefix: define-this-if-not-using-nsDomain,

  domainPrefixes:
    dev: dev.
    stg: stg.
    prod: ''
    local: ''

slicWatch:
  # To create dashboards alarms for all stacks, configure
  # an SNS Topic that is accessible from your target account(s).
  # If you are not sure what to do, or don't want the additional
  # cost of alarms and dashboards, set 'enabled' to false
  enabled: false
