slicUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${self:provider.stage}-user-pool
    UsernameAttributes: [email]
    AutoVerifiedAttributes: [email]

slicUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:provider.stage}-user-pool-client
    ExplicitAuthFlows: [ADMIN_NO_SRP_AUTH]
    RefreshTokenValidity: 30
    UserPoolId:
      Ref: slicUserPool

slicIdentityPool:
  Type: AWS::Cognito::IdentityPool
  Properties:
    AllowUnauthenticatedIdentities: true
    CognitoIdentityProviders:
      - ClientId:
          Ref: slicUserPoolClient
        ProviderName: { Fn::GetAtt: [slicUserPool, ProviderName] }

slicUserPoolArn:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /${self:provider.stage}/user-service/user-pool-arn
    Type: String
    Value: !GetAtt slicUserPool.Arn

userPoolIdParameter:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /${self:provider.stage}/user-service/user-pool-id
    Type: String
    Value: !Ref slicUserPool

userServiceNameParameter:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /${self:provider.stage}/user-service/url
    Type: String
    Value:
      Fn::Join:
        - ''
        - - 'https://'
          - !Ref ApiGatewayRestApi
          - '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/user/'

slicAuthenticatedIdentityPoolRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: 'Allow'
          Principal:
            Federated: 'cognito-identity.amazonaws.com'
          Action:
            - 'sts:AssumeRoleWithWebIdentity'
          Condition:
            StringEquals:
              'cognito-identity.amazonaws.com:aud':
                Ref: slicIdentityPool
            ForAnyValue:StringLike:
              'cognito-identity.amazonaws.com:amr': authenticated
    Policies:
      - PolicyName: ${self:provider.stage}-cognito-authenticated-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - mobiletargeting:PutEvents
              Resource:
                - "*"
            - Effect: Allow
              Action:
                - mobiletargeting:UpdateEndpoint
              Resource:
                - "arn:aws:mobiletargeting:eu-west-1:935672627075:apps/f372bb5285ef4e8eaa697bac737bc002/*"
            - Effect: Allow
              Action:
                - cognito-identity:*
                - cognito-sync:*
              Resource: '*'
              
slicUnauthenticatedIdentityPoolRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: 'Allow'
          Principal:
            Federated: 'cognito-identity.amazonaws.com'
          Action:
            - 'sts:AssumeRoleWithWebIdentity'
          Condition:
            StringEquals:
              'cognito-identity.amazonaws.com:aud':
                Ref: slicIdentityPool
            ForAnyValue:StringLike:
              'cognito-identity.amazonaws.com:amr': unauthenticated
    Policies:
      - PolicyName: ${self:provider.stage}-cognito-authenticated-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-identity:*
                - cognito-sync:*
              Resource: '*'
            - Effect: Allow
              Action:
                - mobiletargeting:PutEvents
              Resource:
                - "*"
            - Effect: Allow
              Action:
                - mobiletargeting:UpdateEndpoint
              Resource:
                - "arn:aws:mobiletargeting:eu-west-1:935672627075:apps/f372bb5285ef4e8eaa697bac737bc002/*"
            

slicIdentityPoolRoleAttachment:
  Type: AWS::Cognito::IdentityPoolRoleAttachment
  Properties:
    IdentityPoolId:
      Ref: slicIdentityPool
    Roles:
      authenticated: { Fn::GetAtt: [slicAuthenticatedIdentityPoolRole, Arn] }
      unauthenticated: { Fn::GetAtt: [slicUnauthenticatedIdentityPoolRole, Arn] }
      
