service: logging-service

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

provider:
  name: aws
  stage: ${opt:stage, 'local'}
  region: ${opt:region, '${self:custom.defaultRegions.${self:provider.stage}}'}
  runtime: python3.6
  tracing: true
  iamRoleStatements: ${file(./sls-iam-role-statements.yml)}

custom:
  defaultRegions: ${file(../common-config.json):defaultRegions}
  pythonRequirements:
    slim: true
    useDownloadCache: true
    useStaticCache: true
    dockerizePip: non-linux

functions: ${file(./sls-functions.yml)}

resources:
  Outputs:
    loggingFunctionArn:
      Value: !GetAtt LogForwarderLambdaFunction.Arn
      Export:
        Name: ${self:provider.stage}-log-forwarder-function-arn

  # NOTE: /logging/logzio/token must be added manually as a SecretString

  Resources:
    logzioFormatParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /logging/logzio/format
        Type: String
        Value: json

    logzioUrlParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /logging/logzio/url
        Type: String
        Value: https://listener.logz.io:8071

    logzioTypeParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /logging/logzio/type
        Type: String
        Value: cloudwatch-logs
