  Type: AWS::IAM::Role
  Properties:
    RoleName: ${self:custom.stage}-slic-codebuild-role
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
          Action: [sts:AssumeRole]
    Path: /
    Policies:
      - PolicyName: ${self:custom.stage}-slic-codebuild-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: [sts:AssumeRole]
              Resource:
                - arn:aws:iam::${self:custom.accountIds.dev}:role/slic-cicd-deployment-role
            - Effect: Allow
              Action: [secretsmanager:GetSecretValue]
              Resource:
                - arn:aws:secretsmanager:#{AWS::Region}:#{AWS::AccountId}:secret:CICD*
            - Effect: Allow
              Action:
                - s3:DeleteObject
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:ListBucket
                - s3:PutObject
                - s3:GetBucketPolicy
                - s3:GetEncryptionConfiguration
                - s3:PutEncryptionConfiguration
              Resource:
                - arn:aws:s3:::codepipeline-${self:custom.region}-*
                - arn:aws:s3:::${self:custom.buildBucket}
                - arn:aws:s3:::${self:custom.buildBucket}/*
            - Effect: Allow
              Action:
                - cloudformation:Describe*
              Resource:
                - arn:aws:cloudformation:eu-west-1:*:stack/${self:custom.serviceName}-${self:custom.stage}/*
            - Effect: Allow
              Action:
                - lambda:Get*
                - lambda:List*
                - lambda:CreateFunction
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - lambda:AddPermission
                - lambda:CreateAlias
                - lambda:DeleteFunction
                - lambda:InvokeFunction
                - lambda:PublishVersion
                - lambda:RemovePermission
                - lambda:Update*
              Resource:
                - arn:aws:lambda:eu-west-1:*:function:${self:custom.serviceName}-${self:custom.stage}-*
            - Effect: Allow
              Action:
                - lambda:AddPermission
                - lambda:CreateAlias
                - lambda:DeleteFunction
                - lambda:InvokeFunction
                - lambda:PublishVersion
                - lambda:RemovePermission
                - lambda:Update*
              Resource:
                - arn:aws:lambda:eu-west-1:*:function:${self:custom.serviceName}-${self:custom.stage}-*
            - Effect: Allow
              Action:
                - apigateway:GET
                - apigateway:POST
                - apigateway:PUT
                - apigateway:DELETE
              Resource:
                - arn:aws:apigateway:*::/restapis*
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - arn:aws:iam::*:role/*
            - Effect: Allow
              Action: kinesis:*
              Resource:
                - arn:aws:kinesis:*:*:stream/${self:custom.serviceName}-${self:custom.stage}-eu-west-1
            - Effect: Allow
              Action:
                - iam:GetRole
                - iam:CreateRole
                - iam:PutRolePolicy
                - iam:DeleteRolePolicy
                - iam:DeleteRole
              Resource:
                - arn:aws:iam::*:role/${self:custom.serviceName}-${self:custom.stage}-eu-west-1-lambdaRole
            - Effect: Allow
              Action: sqs:*
              Resource:
                - arn:aws:sqs:*:*:${self:custom.serviceName}-${self:custom.stage}-eu-west-1
            - Effect: Allow
              Action:
                - cloudwatch:GetMetricStatistics
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:DeleteLogGroup
              Resource:
                - arn:aws:logs:eu-west-1:*:*
            - Effect: Allow
              Action:
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:eu-west-1:*:*
            - Effect: Allow
              Action:
                - logs:DescribeLogStreams
                - logs:DescribeLogGroups
                - logs:FilterLogEvents
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - events:Put*
                - events:Remove*
                - events:Delete*
              Resource:
                - arn:aws:events:*:*:rule/${self:custom.serviceName}-${self:custom.stage}-eu-west-1
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - arn:aws:dynamodb:*:*:table/*
            - Effect: Allow
              Action:
                - s3:CreateBucket
                - s3:GetEncryptionConfiguration
                - s3:PutEncryptionConfiguration
              Resource:
                - arn:aws:s3:::*
