service: ${self:custom.serviceName}

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: ${self:custom.runtime}
  stage: ${self:custom.stage}
  region: ${self:custom.region}

custom: ${file(./custom.yml)}

resources:
  Resources: ${file(./sls-resources.yml.js)}
