service: deployment-target-resources

custom:
  stage: ${opt:stage, 'cicd'}
  region: eu-west-1
  runtime: nodejs8.10
  accountIds:
    cicd: 285982925560

provider:
  name: aws
  runtime: ${self:custom.runtime}
  stage: ${self:custom.stage}
  region: ${self:custom.region}

resources:
  Resources:
    deploymentRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: slic-cicd-deployment-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS: ${self:custom.accountIds.cicd}
              Action: [sts:AssumeRole]
        Path: /

    deploymentPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: slic-cicd-deployment-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cloudformation:List*
                - cloudformation:Get*
                - cloudformation:PreviewStackUpdate
                - cloudformation:ValidateTemplate
                - cloudformation:CreateStack
                - cloudformation:CreateUploadBucket
                - cloudformation:DeleteStack
                - cloudformation:Describe*
                - cloudformation:UpdateStack
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - apigateway:GET
                - apigateway:POST
                - apigateway:PUT
                - apigateway:DELETE
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - iam:GetRole
                - iam:CreateRole
                - iam:PassRole
                - iam:PutRolePolicy
                - iam:DeleteRolePolicy
                - iam:DeleteRole
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - s3:CreateBucket
                - s3:GetBucket*
                - s3:GetBucketPolicy
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:GetEncryptionConfiguration
                - s3:PutEncryptionConfiguration
                - s3:SetBucketEncryption
                - s3:ListBucket
                - s3:PutObject
                - s3:PutBucketPolicy
                - s3:PutBucketWebsite
              Resource:
                - arn:aws:s3:::slic-*
            - Effect: Allow
              Action:
                - lambda:Get*
                - lambda:List*
                - lambda:CreateFunction
                - lambda:AddPermission
                - lambda:CreateAlias
                - lambda:DeleteFunction
                - lambda:InvokeFunction
                - lambda:PublishVersion
                - lambda:RemovePermission
                - lambda:Update*
              Resource:
                - arn:aws:lambda:${self:custom.region}:*:function:*
            - Effect: Allow
              Action:
                - cloudfront:CreateDistribution
                - cloudfront:GetDistribution
                - cloudfront:UpdateDistribution
                - cloudfront:TagResource
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - dynamodb:CreateTable
                - dynamodb:DescribeTable
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: 'arn:aws:dynamodb:${self:custom.region}:*:*'
            - Effect: Allow
              Action: 'sqs:*'
              Resource:
                - arn:aws:sqs:*:*:*
            - Effect: Allow
              Action:
                - cloudwatch:GetMetricStatistics
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:DeleteLogGroup
              Resource:
                - arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
                - logs:DescribeLogStreams
                - logs:DescribeLogGroups
                - logs:FilterLogEvents
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - events:Put*
                - events:Remove*
                - events:Delete*
              Resource:
                - 'arn:aws:events:*:*:rule/*'
            - Effect: Allow
              Action:
                - 'acm:RequestCertificate'
                - 'acm:DeleteCertificate'
                - 'acm:DescribeCertificate'
                - 'acm:AddTagsToCertificate'
                - 'route53:GetChange'
                - 'route53:GetHostedZone'
                - 'route53:CreateHostedZone'
                - 'route53:DeleteHostedZone'
                - 'route53:ChangeResourceRecordSets'
                - 'route53:ChangeTagsForResource'
                - 'route53:ListResourceRecordSets'
                - 'route53:ListHostedZones'
                - 'route53:ListQueryLoggingConfigs'
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - events:Put*
                - events:Remove*
                - events:Delete*
              Resource:
                - 'arn:aws:events:*:*:rule/*'
            - Effect: Allow
              Action:
                # Start permissions required for integration tests
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminDeleteUser
                - cognito-idp:AdminInitiateAuth
                - cognito-idp:AdminRespondToAuthChallenge
                # End permissions required for integration tests
                - cognito-idp:CreateUserPool*
                - cognito-idp:DeleteUserPool*
                - cognito-idp:ListUserPool*
                - cognito-identity:CreateIdentityPool
                - cognito-identity:DeleteIdentityPool
                - cognito-identity:UpdateIdentityPool
                - cognito-identity:ListIdentityPools
                - cognito-identity:GetIdentityPoolRoles
                - cognito-identity:SetIdentityPoolRoles
              Resource:
                - '*'

        Roles:
          - Ref: deploymentRole
