# Integration tests CodeBuild
version: 0.2
phases:
  install:
    commands:
      - cd integration-tests
      - npm install
  build:
    commands:
      - npm test
artifacts:
  files:
    - integration-tests/**/*
